avatar_size:
  default: 45
  type: string
  min: 45
  max: 200
  description:
    en: "Set the size of post avatars in pixels (default: 45)."
    de: "Ändere die Größe von Avataren in Beiträgen (Einheit: Pixel, Standard: 45)"
avatar_spacing_right:
  default: 0
  type: string
  description:
    en: "Add extra spacing (in pixels) to the right-hand side of post avatars for a more balanced design with larger avatars."
    de: "Füge einen Abstand (in Pixeln) zwischen Avataren und dem Beitragstext hinzu"
avatar_border_radius:
  default: 50%
  type: string
  description:
    en: "Set the border radius of avatars across the forum. Can use any valid CSS size (e.g. px, %, em)."
    de: "Ändere den border-radius von allen Avataren dieses Forums. Unterstützt jede gültige CSS-Einheit (e.g. px, %, em)."
